### ISSUE TITLE
Hassio Integration problem

### ISSUE THREAD

**Issue by mr-varga** [fredericvl/py-agua-iot#24]
I have the pellet stove (Anselmo Cola) with the same WiFi module. I try to setup the hassio custom component but unfortunately without success. 
I can configure the connection with this data:
<img src="https://community-assets.home-assistant.io/original/4X/7/7/a/77afc93a1249c74cd377964a4a579e40786591fb.jpeg" />
This is the log:
`2021-12-18 23:53:30 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
resp = await request_handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 181, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 157, in post
return await super().post(request, flow_id)
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
result = await method(view, request, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
result = await self._flow_mgr.async_configure(flow_id, data)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 252, in async_configure
result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 325, in _async_handle_step
result: FlowResult = await getattr(flow, method)(user_input)
File "/config/custom_components/aguaiot/config_flow.py", line 67, in async_step_user
await self.hass.async_add_executor_job(agua_iot, api_url, customer_code, email, password, gen_uuid, login_api_url, brand_id)
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/local/lib/python3.9/site-packages/py_agua_iot/__init__.py", line 92, in __init__
self._login()
File "/usr/local/lib/python3.9/site-packages/py_agua_iot/__init__.py", line 96, in _login
self.login()
File "/usr/local/lib/python3.9/site-packages/py_agua_iot/__init__.py", line 186, in login
claimset = jwt.decode(res['token'], verify=False)
File "/usr/local/lib/python3.9/site-packages/jwt/api_jwt.py", line 119, in decode
decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
File "/usr/local/lib/python3.9/site-packages/jwt/api_jwt.py", line 86, in decode_complete
raise DecodeError(
jwt.exceptions.DecodeError: It is required that you pass in a value for the "algorithms" argument when calling decode().`

Can some help me to solve or correct this problem, please?

**Comment by TorgeTorge** [comment]
You just need to edit the manifest.json( found in \config\custom_components\aguaiot\manifest.json) by replace this two lines:
`  "version": "0.0.7",
  "requirements": ["py-agua-iot==0.0.7"],`

**with:**

`  "version": "0.0.8",
  "requirements": ["py-agua-iot==0.0.8"],`

**Comment by mr-varga** [comment]
After update HA to core-2022.3.0 the integration stop working with this error:

`2022-03-03 02:44:23 ERROR (SyncWorker_4) [homeassistant.util.package] Unable to install package py-agua-iot==0.0.8: ERROR: Cannot install py-agua-iot==0.0.8 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
2022-03-03 02:44:23 INFO (SyncWorker_0) [homeassistant.util.package] Attempting install of py-agua-iot==0.0.8
2022-03-03 02:44:28 ERROR (SyncWorker_0) [homeassistant.util.package] Unable to install package py-agua-iot==0.0.8: ERROR: Cannot install py-agua-iot==0.0.8 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
2022-03-03 02:44:28 INFO (SyncWorker_2) [homeassistant.util.package] Attempting install of py-agua-iot==0.0.8
2022-03-03 02:44:33 ERROR (SyncWorker_2) [homeassistant.util.package] Unable to install package py-agua-iot==0.0.8: ERROR: Cannot install py-agua-iot==0.0.8 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
2022-03-03 02:44:33 ERROR (MainThread) [homeassistant.setup] Setup failed for aguaiot: Requirements for aguaiot not found: ['py-agua-iot==0.0.8'].`

**Comment by milouzzzz** [comment]
same here. Error with the requirements.
Downgraded to previous HA core solved the problem.
