### ISSUE TITLE
homeassistant 2022.6.8 issue with nobis stove

### ISSUE THREAD

**Issue by thetux07** [fredericvl/py-agua-iot#34]
i would like integrate my stove but i have this error 

2022-08-19 17:52:03.514 ERROR (MainThread) [homeassistant.components.climate] Error adding entities for domain climate with platform aguaiot
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 673, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 776, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 572, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 272, in state_attributes
    self.current_temperature,
  File "/config/custom_components/aguaiot/climate.py", line 164, in current_temperature
    return self._device.air_temperature
  File "/usr/local/lib/python3.10/site-packages/py_agua_iot/__init__.py", line 583, in air_temperature
    return float(self.__get_information_item('temp_air_get'))
  File "/usr/local/lib/python3.10/site-packages/py_agua_iot/__init__.py", line 430, in __get_information_item
    formula = self.__register_map_dict[item]['formula']
KeyError: 'temp_air_get'
2022-08-19 17:52:03.628 ERROR (MainThread) [homeassistant.components.climate] Error while setting up aguaiot platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 289, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 673, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 776, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 572, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 272, in state_attributes
    self.current_temperature,
  File "/config/custom_components/aguaiot/climate.py", line 164, in current_temperature
    return self._device.air_temperature
  File "/usr/local/lib/python3.10/site-packages/py_agua_iot/__init__.py", line 583, in air_temperature
    return float(self.__get_information_item('temp_air_get'))
  File "/usr/local/lib/python3.10/site-packages/py_agua_iot/__init__.py", line 430, in __get_information_item
    formula = self.__register_map_dict[item]['formula']
KeyError: 'temp_air_get'

can you help me ?
thank you

**Comment by thetux07** [comment]
hello,
after searching by browsing the api doc (https://nobis.agua-iot.com/api-docs) I realized that the call had to be made on "temp_air2_get" and not "temp_air_get"
it works fine now. would it be possible to see the heating schedule and be able to change the speed of the fan?
thank you
