### ISSUE TITLE
pelletstove Viktor c-hvr recognized but no entities

### ISSUE THREAD

**Issue by cvdpol01** [fredericvl/py-agua-iot#43]
Hi fredericvl, 

I am working for the first time with Homeassistant and am surprised about all possibilities. I am very interested in getting my pellet stove on it and let it work with my temperature sensor at home.
Now I tried to make contact with my pelletstove Nordic Fire Viktor c-hvr on homeassistant. The stove has been recognized and logged in but I get no entities. Any idea what I am doing wrong or what I am missing?

**Comment by cvdpol01** [comment]
Hello Fredericvl,
The pelletstove is recognized in homeassitant with the rightname, that looks good. But I'm missing the entities like the temprature and to power it on or off. When I look in the logging I see the following: 

2023-01-08 19:09:42.376 ERROR (MainThread) [homeassistant.components.climate] Error adding entities for domain climate with platform aguaiot
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 438, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 621, in _async_add_entity
    capabilities=entity.capability_attributes,
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 264, in capability_attributes
    self.hass, self.min_temp, self.temperature_unit, self.precision
  File "/config/custom_components/aguaiot/climate.py", line 154, in min_temp
    return self._device.min_temp
  File "/usr/local/lib/python3.10/site-packages/py_agua_iot/__init__.py", line 575, in min_temp
    return self.__get_information_item_min('temp_air_set')
  File "/usr/local/lib/python3.10/site-packages/py_agua_iot/__init__.py", line 448, in __get_information_item_min
    value = int(self.__register_map_dict[item]['set_min'])
KeyError: 'temp_air_set'
2023-01-08 19:09:42.382 ERROR (MainThread) [homeassistant.components.climate] Error while setting up aguaiot platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 297, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 438, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 621, in _async_add_entity
    capabilities=entity.capability_attributes,
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 264, in capability_attributes
    self.hass, self.min_temp, self.temperature_unit, self.precision
  File "/config/custom_components/aguaiot/climate.py", line 154, in min_temp
    return self._device.min_temp
  File "/usr/local/lib/python3.10/site-packages/py_agua_iot/__init__.py", line 575, in min_temp
    return self.__get_information_item_min('temp_air_set')
  File "/usr/local/lib/python3.10/site-packages/py_agua_iot/__init__.py", line 448, in __get_information_item_min
    value = int(self.__register_map_dict[item]['set_min'])
KeyError: 'temp_air_set'
2023-01-08 19:09:52.491 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.dockker_tst is taking over 10 seconds
2023-01-08 19:10:02.642 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"

To you know what is going wrong and what can I do the make it working?

Best regard and thanks for your help,

**Comment by vincentwolsink** [comment]
Please try the newest version of the Home Assistant plugin.
