### ISSUE TITLE
Unable to get info About my Pallet stove through API

### ISSUE THREAD

**Issue by demokedes** [fredericvl/py-agua-iot#44]
Based on the API documentation, I've tried to connect to platform and get some information about my pellet stove. In the bellow example, I wanted to get air temperature. 
This is the code I am running: 
*************************************************************************
_from py_agua_iot import agua_iot

# https://evastampaggi.agua-iot.com => Agua IOT API URL for Eva Calor
# 635987 => customer code of Eva Calor
# 1c3be3cd-360c-4c9f-af15-1f79e9ccbc2a => random UUID (you can generate one here: https://www.uuidgenerator.net/version4)
# brand_id="1" => optional brand id (should always be "1" but can be overridden just in case)
# login_api_url="" => optional separate login URL (used for Piazzetta for example)
connection = agua_iot("https://piazzetta.agua-iot.com", "458632", "rok.rogelj@gmail.com", "xxxxxxxx", "bb41c60b-7969-495e-8290-6515fc67f41e", brand_id="1", login_api_url="https://piazzetta.iot.web2app.it/api/bridge/endpoint/")

# Print the current air temperature for each device
for device in connection. Devices:
  print(device.name + ": " + str(device.air_temperature))_
**********************************************************************************************

And this is the error response:
---------------------------------------------------------------------------
_KeyError                                  Traceback (most recent call last)
[<ipython-input-8-c7a711e3c986>](https://localhost:8080/#) in <module>
      6 # brand_id="1" => optional brand id (should always be "1" but can be overridden just in case)
      7 # login_api_url="" => optional separate login URL (used for Piazzetta for example)
----> 8 connection = agua_iot("https://piazzetta.agua-iot.com/", "458632", "[rok.rogelj@gmail.com](mailto:rok.rogelj@gmail.com)", "xxxxxxxxx", "bb41c60b-7969-495e-8290-6515fc67f41e", brand_id="1", login_api_url="https://piazzetta.iot.web2app.it/api/bridge/endpoint/")
      9 
     10 # Print the current air temperature for each device

2 frames
[/usr/local/lib/python3.8/dist-packages/py_agua_iot/__init__.py](https://localhost:8080/#) in login(self)
    181 
    182         res = response.json()
--> 183         self.token = res['token']
    184         self.refresh_token = res['refresh_token']
    185 

KeyError: 'token'_
**************************************************************************************************
Any idea what I am doing wrong?
Thank you in advance!

**Comment by Donder24** [comment]
Hi all,
Since yesterday evening I get the same issue.
Anyone experience with this? 

Thanks!


> Logger: homeassistant.components.climate
> Source: custom_components/aguaiot/climate.py:74
> Integration: Klimaat (documentation, issues)
> First occurred: 13:31:44 (1 occurrences)
> Last logged: 13:31:44
> 
> Error while setting up aguaiot platform for climate
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 289, in _async_setup_platform
>     await asyncio.shield(task)
>   File "/config/custom_components/aguaiot/climate.py", line 74, in async_setup_entry
>     agua = await hass.async_add_executor_job(agua_iot, api_url, customer_code, email, password, gen_uuid, login_api_url, brand_id)
>   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/usr/local/lib/python3.10/site-packages/py_agua_iot/__init__.py", line 92, in __init__
>     self._login()
>   File "/usr/local/lib/python3.10/site-packages/py_agua_iot/__init__.py", line 96, in _login
>     self.login()
>   File "/usr/local/lib/python3.10/site-packages/py_agua_iot/__init__.py", line 183, in login
>     self.token = res['token']
> KeyError: 'token'
>

**Comment by eternalpolo** [comment]
My stove (Piazzetta too) is inavailable since some days.
I have the same error in the logs:


`[homeassistant.components.climate] Error while setting up aguaiot platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 289, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/aguaiot/climate.py", line 74, in async_setup_entry
    agua = await hass.async_add_executor_job(agua_iot, api_url, customer_code, email, password, gen_uuid, login_api_url, brand_id)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/py_agua_iot/__init__.py", line 92, in __init__
    self._login()
  File "/usr/local/lib/python3.10/site-packages/py_agua_iot/__init__.py", line 96, in _login
    self.login()
  File "/usr/local/lib/python3.10/site-packages/py_agua_iot/__init__.py", line 183, in login
    self.token = res['token']
KeyError: 'token'
`
I've tries to delete my stove and start a new integration but i have the message "Unknown error occured":

![Screenshot_20230118_225836_Home Assistant.jpg](https://user-images.githubusercontent.com/73798100/213304656-07c42e81-e7b2-44fc-a512-7e9d0fb913ed.jpg)

And in the logs i have:

`Cette erreur provient d'une intégration personnalisée

Logger: aiohttp.server
Source: custom_components/aguaiot/config_flow.py:67
Integration: Micronova Agua IOT (documentation)
First occurred: 22:18:00 (9 occurrences)
Last logged: 22:58:31

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 81, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 180, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 286, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 374, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/aguaiot/config_flow.py", line 67, in async_step_user
    await self.hass.async_add_executor_job(agua_iot, api_url, customer_code, email, password, gen_uuid, login_api_url, brand_id)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/py_agua_iot/__init__.py", line 92, in __init__
    self._login()
  File "/usr/local/lib/python3.10/site-packages/py_agua_iot/__init__.py", line 96, in _login
    self.login()
  File "/usr/local/lib/python3.10/site-packages/py_agua_iot/__init__.py", line 183, in login
    self.token = res['token']
KeyError: 'token'
`

Someone else have this problem or find a solution?

**Comment by Donder24** [comment]
For those who are still having this issue: [https://github.com/fredericvl/py-agua-iot/issues/49](url)

There are now 2 issues opened
