### ISSUE TITLE
Error when logging in

### ISSUE THREAD

**Issue by camd87** [fredericvl/py-agua-iot#70]
Hey everyone.  Python noob here.

I am getting this error when trying to connect to MySuperior.  
KeyError: 'token'

I added a print statement to the code to see what was in res, and this is what is coming up:
{"Error":"INVALID_APP_ERROR","Success":false,"Source":"BRIDGE"}

Anyone else have the same issue?  Any fix?

Here is my connection string (with the login details blanked for obvious reasons)

connection = agua_iot("https://piazzetta.agua-iot.com", "458632", "manager@*******.com.au", "mypassword", "cb417e45-35c5-4ef4-9035-dfc569db755f", brand_id="1", login_api_url="https://piazzetta-iot.app2cloud.it/api/bridge/endpoint/")

Thanks for your help!

**Comment by vincentwolsink** [comment]
Please use the latest version (v0.0.22) and add parameter `api_login_application_version="1.9.5"`

**Comment by camd87** [comment]
Thanks @vincentwolsink very much for your help.
I received the below (sensitive info blanked out) - any ideas?  I installed the latest version.
Thanks again!
>>> %Run fire.py
Traceback (most recent call last):
  File "/home/pi/fire.py", line 2, in <module>
    connection = agua_iot("https://piazzetta.agua-iot.com", "458632", "manager@sierraescape.com.au", "#####", "d153da78-b247-4ce1-a1b6-d21b45cb1eb7", brand_id="1", login_api_url="https://piazzetta-iot.app2cloud.it/api/bridge/endpoint/", api_login_application_version="1.9.5")
  File "/usr/local/lib/python3.7/dist-packages/py_agua_iot/__init__.py", line 140, in __init__
    self._login()
  File "/usr/local/lib/python3.7/dist-packages/py_agua_iot/__init__.py", line 144, in _login
    self.login()
  File "/usr/local/lib/python3.7/dist-packages/py_agua_iot/__init__.py", line 229, in login
    self.token = res["token"]
KeyError: 'token'
